# Generated by Django 6.0 on 2025-12-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("raw_description", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("film", "Film"),
                            ("photo", "Photography"),
                            ("article", "Article"),
                            ("podcast", "Podcast"),
                            ("design", "Design"),
                        ],
                        max_length=50,
                    ),
                ),
                ("thumbnail", models.ImageField(upload_to="thumbnails/")),
                ("created_at", models.DateField()),
                ("link", models.URLField(blank=True)),
            ],
        ),
    ]
